#!/usr/bin/env python3
"""Managed linter checks — tier 1 of the enforcement split. Re-vendored into a fork by
`./bootstrap.sh --update`; **do not edit this file in a fork** — your edits are overwritten on
the next update. Fork-local checks go in `tools/lint.py` (the wrapper), which imports this
module and passes its own checks to `run(extra_checks=...)`.

ERROR blocks the commit; WARN advises. The ERROR/WARN assignment IS the split: a
check is ERROR only if a violation is unambiguously wrong; a loose mechanical shadow
of a semantic rule is always WARN (a high-precision backstop, never a substitute for
judgment). Each check's docstring names the governance rule it shadows — the linter
is indexed to the semantic layer, not a replacement for it.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC_DIRS = ["docs"]  # directories holding governed markdown
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
FENCE_RE = re.compile(r"^```.*?^```", re.S | re.M)  # fenced code blocks

errors = []
warnings = []


def error(path, msg):
    errors.append(f"ERROR  {os.path.relpath(path, ROOT)}: {msg}")


def warn(path, msg):
    warnings.append(f"WARN   {os.path.relpath(path, ROOT)}: {msg}")


def md_files():
    yield os.path.join(ROOT, "README.md")
    for d in DOC_DIRS:
        for dirpath, _, names in os.walk(os.path.join(ROOT, d)):
            for n in names:
                if n.endswith(".md"):
                    yield os.path.join(dirpath, n)


def check_relative_links(path, text):
    """Shadows: 'every pointer targets an existing file'. Mechanical → ERROR.
    Links inside fenced code blocks are illustrative (a README skeleton, or a
    forward-reference to a yet-to-be-generated artifact), not live pointers — skip them."""
    text = FENCE_RE.sub("", text)
    for m in LINK_RE.finditer(text):
        target = m.group(1).split("#")[0]
        if not target or "://" in target or target.startswith("mailto:"):
            continue
        resolved = os.path.normpath(os.path.join(os.path.dirname(path), target))
        if not os.path.exists(resolved):
            error(path, f"broken relative link: {m.group(1)}")


def check_opening_thesis(path, text):
    """Shadows: 'open with a one-sentence thesis'. Loose backstop → always WARN."""
    body = re.sub(r"^---\n.*?\n---\n", "", text, flags=re.S)  # skip frontmatter
    lines = [l for l in body.splitlines() if l.strip() and not l.startswith("#")]
    if lines and len(lines[0]) > 400:
        warn(path, "opening line is very long — is it still a one-sentence thesis?")


DECISION_STATUSES = {"decided", "superseded"}
_FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)
_FM_KEY_RE = re.compile(r"^([A-Za-z_][\w-]*):\s*(.*)$")


def _frontmatter(text):
    """Flat dict of top-level `key: value` pairs from a leading `---`…`---` block;
    {} if absent. Sufficient for `status:`/`superseded_by:` — not a full YAML parser."""
    m = _FM_RE.match(text)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        km = _FM_KEY_RE.match(line)
        if km:
            out[km.group(1)] = km.group(2).strip().strip("\"'")
    return out


def check_decision_status(path, text):
    """Shadows: 'a decision doc declares live-vs-dead at the file, not only in the
    verdict registry' (docs/decisions/README.md). Every decision doc — a `*.md` (not
    README) whose immediate parent dir is `decisions/` anywhere under `docs/` — carries
    frontmatter `status:` in {decided, superseded}; a `superseded` doc needs a
    `superseded_by:` resolving to an existing sibling. Mechanical → ERROR. Self-gates:
    a repo with no `docs/**/decisions/` dir never trips it. Depth-robust so module-internal
    `docs/<module>/decisions/` dirs are covered without re-anchoring."""
    parts = os.path.relpath(path, ROOT).split(os.sep)
    if os.path.basename(path) == "README.md" or len(parts) < 2:
        return
    if "docs" not in parts[:-1] or parts[-2] != "decisions":
        return
    fm = _frontmatter(text)
    status = fm.get("status")
    if status is None:
        error(path, "decision doc missing frontmatter `status:` (expected decided|superseded)")
        return
    if status not in DECISION_STATUSES:
        error(path, f"decision doc `status: {status}` not in {sorted(DECISION_STATUSES)}")
        return
    if status == "superseded":
        target = fm.get("superseded_by")
        if not target:
            error(path, "`status: superseded` requires `superseded_by:` (a reversal with no "
                        "successor is itself a new decision doc — see docs/decisions/README.md)")
            return
        resolved = os.path.normpath(os.path.join(os.path.dirname(path), target))
        if not os.path.exists(resolved):
            error(path, f"`superseded_by: {target}` resolves to no file")


def check_stamp_drift():
    """Shadows: 'a fork's managed checks track CMS canonical' (WS2 propagation). Advisory →
    WARN. **No hashing here** — bash is the sole hash producer: it stamps the fork's
    `tools/.cms-version` at vendor time and writes a committed canonical `tools/.cms-manifest`
    in the CMS clone; this check just string-compares the two. Self-gates to silence (never a
    false alarm) when there's no local stamp (CMS itself, or an unmigrated legacy fork) or no
    reachable canonical (`CMS_SRC` unset, or its manifest missing — a disconnected fork: honest
    dormancy, no-worse-than-today). Repo-level: runs once, not per file."""
    stamp_file = os.path.join(ROOT, "tools", ".cms-version")
    if not os.path.exists(stamp_file):
        return
    src = os.environ.get("CMS_SRC")
    if not src:
        return
    manifest = os.path.join(src, "tools", ".cms-manifest")
    if not os.path.exists(manifest):
        return
    with open(stamp_file, encoding="utf-8") as f:
        local = f.read().strip()
    with open(manifest, encoding="utf-8") as f:
        canonical = f.read().strip()
    if local != canonical:
        warn(stamp_file, "managed checks differ from CMS canonical — run "
                         "`./bootstrap.sh --update <this repo>` from the CMS clone to refresh")


# The managed check set. Fork-local checks are NOT added here — they live in the
# tools/lint.py wrapper and reach run() via extra_checks.
SHARED_CHECKS = [check_relative_links, check_opening_thesis, check_decision_status]
# Repo-level managed checks: run once over the repo, not per markdown file.
REPO_CHECKS = [check_stamp_drift]


def run(extra_checks=()):
    """Run the managed checks plus any fork-local `extra_checks` over the governed corpus.
    Returns a process exit code (1 if any ERROR, else 0)."""
    checks = list(SHARED_CHECKS) + list(extra_checks)
    for path in md_files():
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as f:
            text = f.read()
        for check in checks:
            check(path, text)

    for repo_check in REPO_CHECKS:
        repo_check()

    for w in warnings:
        print(w)
    for e in errors:
        print(e)
    if errors:
        print(f"\n{len(errors)} error(s) — commit blocked. (Warnings are advisory.)")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(run())
